import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from datetime import datetime

# --- Configuration Placeholders (Should be set via environment variables in production) ---
SMTP_SERVER = "smtp.example.com"  # Placeholder SMTP Server
SMTP_PORT = 587  # Standard TLS port
SMTP_USERNAME = "soc_alert@example.com"
SMTP_PASSWORD = "YOUR_SECURE_PASSWORD"  # MUST use an App Password, not main password
DEFAULT_RECIPIENT = "soc_admin@example.com"
SENDER_EMAIL = "AnomalyDetector@example.com"


def send_email_alert(alert_data: dict, recipient_email: str = DEFAULT_RECIPIENT):
    """
    Sends an email notification for a critical anomaly detection event.

    Args:
        alert_data (dict): A dictionary containing the final explained alert.
                           Expected keys: 'timestamp', 'classification', 'reason'.
        recipient_email (str): The email address to send the alert to.
    """
    if not all([SMTP_SERVER, SMTP_USERNAME, SMTP_PASSWORD]):
        print("🚨 ALERTING ERROR: SMTP credentials are not fully configured. Email not sent.")
        return False

    try:
        classification = alert_data.get('classification', 'UNKNOWN ANOMALY')
        reason = alert_data.get('reason', 'No explanation available.')
        timestamp_str = alert_data.get('timestamp', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        subject = f"🚨 CRITICAL ALERT: {classification} Detected at {timestamp_str}"

        # Construct the plain text and HTML body
        text_body = f"""
        ANOMALY DETECTION SYSTEM ALERT

        Timestamp: {timestamp_str}
        Classification: {classification}
        ------------------------------------------
        Reason/Explanation:
        {reason}
        ------------------------------------------
        Action Recommended: Investigate source/destination traffic immediately.
        """

        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6;">
            <div style="border: 2px solid #CC0000; padding: 20px; border-radius: 8px; background-color: #FFF0F0;">
                <h2 style="color: #CC0000;">🚨 CRITICAL ANOMALY DETECTED</h2>

                <p><strong>Timestamp:</strong> {timestamp_str}</p>
                <p><strong>Classification:</strong> <span style="font-size: 1.1em; font-weight: bold; color: #990000;">{classification}</span></p>

                <hr style="border-top: 1px solid #ddd;">

                <h3>Expert Witness Explanation:</h3>
                <p style="background-color: #F8F8F8; padding: 10px; border-left: 3px solid #CC0000;">
                    {reason}
                </p>

                <p style="margin-top: 20px;"><strong>Action Recommended:</strong> Investigate source/destination traffic immediately.</p>
            </div>
            <p><small>This alert was generated by the ML-Powered Anomaly Detection System.</small></p>
        </body>
        </html>
        """

        # Create the message container
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = SENDER_EMAIL
        msg['To'] = recipient_email

        # Attach parts into message container
        msg.attach(MIMEText(text_body, 'plain'))
        msg.attach(MIMEText(html_body, 'html'))

        # Send the email
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()  # Secure the connection
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.sendmail(SENDER_EMAIL, recipient_email, msg.as_string())

        print(f"✅ Email Alert Sent: {classification} to {recipient_email}")
        return True

    except smtplib.SMTPAuthenticationError:
        print(f"🚨 ALERTING FAILED: SMTP Authentication Error. Check username/password for {SMTP_USERNAME}.")
        return False
    except smtplib.SMTPConnectError:
        print(f"🚨 ALERTING FAILED: Could not connect to SMTP server {SMTP_SERVER}:{SMTP_PORT}.")
        return False
    except Exception as e:
        print(f"🚨 ALERTING FAILED: An unexpected error occurred: {e}")
        return False


# Example usage (for testing/demonstration)
if __name__ == '__main__':
    # This block will typically not run in the final web app environment
    print("Running Notifier Self-Test (Requires valid SMTP config)...")

    mock_alert = {
        'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        'classification': 'SYN_FLOOD_ATTACK',
        'reason': 'The key features contributing to this decision were an unusually high count of connections and a sharply increased serror_rate, indicating many failed handshakes.'
    }

    # NOTE: This will fail unless the constants above are replaced with real credentials/server details.
    # success = send_email_alert(mock_alert, "test_recipient@external.com")
    # print(f"Test result: {'Success' if success else 'Failure'}")
